{% set version = '3.2.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stochvol
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stochvol_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stochvol/stochvol_{{ version }}.tar.gz
  sha256: 5c149912cbb774c0baccc62ee6b78fcdae378595d143a5a17c7bb56f89cd28b3

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0
    - r-rcpparmadillo >=0.9.900
    - r-coda >=0.19
    - libblas
    - liblapack
  run:
    - r-base
    - r-rcpp >=1.0
    - r-rcpparmadillo >=0.9.900
    - r-coda >=0.19

test:
  commands:
    - $R -e "library('stochvol')"           # [not win]
    - "\"%R%\" -e \"library('stochvol')\""  # [win]

about:
  home: https://gregorkastner.github.io/stochvol/
  dev_url: https://github.com/gregorkastner/stochvol
  license: GPL-2.0-or-later
  summary: "Efficient algorithms for fully Bayesian estimation of stochastic volatility (SV)
    models with and without asymmetry (leverage) via Markov chain Monte Carlo (MCMC)
    methods. Methodological details are given in Kastner and Fr\xFChwirth-Schnatter
    (2014) <doi:10.1016/j.csda.2013.01.002> and Hosszejni and Kastner (2019) <doi:10.1007/978-3-030-30611-3_8>;
    the most common use cases are described in Hosszejni and Kastner (2021) <doi:10.18637/jss.v100.i12>
    and Kastner (2016) <doi:10.18637/jss.v069.i05> and the package examples."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: stochvol
# Type: Package
# Title: Efficient Bayesian Inference for Stochastic Volatility (SV) Models
# Version: 3.2.4
# Authors@R: c( person("Darjus", "Hosszejni", role = c("aut", "cre"), email = "darjus.hosszejni@icloud.com", comment = c(ORCID = "0000-0002-3803-691X")), person("Gregor", "Kastner", role = c("aut"), email = "gregor.kastner@aau.at", comment = c(ORCID = "0000-0002-8237-8271")))
# Description: Efficient algorithms for fully Bayesian estimation of stochastic volatility (SV) models with and without asymmetry (leverage) via Markov chain Monte Carlo (MCMC) methods. Methodological details are given in Kastner and Fruhwirth-Schnatter (2014) <doi:10.1016/j.csda.2013.01.002> and Hosszejni and Kastner (2019) <doi:10.1007/978-3-030-30611-3_8>; the most common use cases are described in Hosszejni and Kastner (2021) <doi:10.18637/jss.v100.i12> and Kastner (2016) <doi:10.18637/jss.v069.i05> and the package examples.
# License: GPL (>= 2)
# Depends: R (>= 3.5)
# Imports: Rcpp (>= 1.0), coda (>= 0.19), graphics, stats, utils, grDevices
# Suggests: testthat (>= 2.3.2), mvtnorm, knitr
# LinkingTo: Rcpp, RcppArmadillo (>= 0.9.900)
# RoxygenNote: 7.2.3
# BuildResaveData: best
# VignetteBuilder: knitr
# BugReports: https://github.com/gregorkastner/stochvol/issues
# URL: https://gregorkastner.github.io/stochvol/
# NeedsCompilation: yes
# Packaged: 2024-03-03 11:30:25 UTC; darjushosszejni
# Author: Darjus Hosszejni [aut, cre] (<https://orcid.org/0000-0002-3803-691X>), Gregor Kastner [aut] (<https://orcid.org/0000-0002-8237-8271>)
# Maintainer: Darjus Hosszejni <darjus.hosszejni@icloud.com>
# Repository: CRAN
# Date/Publication: 2024-03-03 12:10:03 UTC
