{% set version = "3.2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stochvol
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stochvol_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stochvol/stochvol_{{ version }}.tar.gz
  sha256: 4a8c092c636344e69a828427c79fca5fe57dd3973d9ddd410074e9e93354f14c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-coda                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0
    - r-rcpparmadillo >=0.9.900
    - r-coda >=0.19
    - libblas
    - liblapack
  run:
    - r-base
    - r-rcpp >=1.0
    - r-rcpparmadillo >=0.9.900
    - r-coda >=0.19

test:
  commands:
    - $R -e "library('stochvol')"           # [not win]
    - "\"%R%\" -e \"library('stochvol')\""  # [win]

about:
  home: https://gregorkastner.github.io/stochvol/
  dev_url: https://github.com/gregorkastner/stochvol
  license: GPL-2.0-or-later
  summary: "Efficient algorithms for fully Bayesian estimation of stochastic volatility (SV) models with and without asymmetry (leverage) via Markov chain Monte Carlo (MCMC) methods. Methodological details are given in Kastner and Frühwirth-Schnatter (2014) <doi:10.1016/j.csda.2013.01.002> and Hosszejni and Kastner (2019)
    <doi:10.1007/978-3-030-30611-3_8>; the most common use cases are described in Hosszejni and Kastner (2021) <doi:10.18637/jss.v100.i12> and Kastner (2016) <doi:10.18637/jss.v069.i05> and the package examples."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
